package modelo;

public enum Personagens {
    PERSONAGEM_LUCAS_M, PERSONAGEM_LUCAS_L, PERSONAGEM_LUCAS_S, PERSONAGEM_LUCAS_P,
    PERSONAGEM_GABI, PERSONAGEM_PAULO, PERSONAGEM_THIAGO, PERSONAGEM_GUILHERME;
}
